version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

sphinx:
  configuration: docs/en/conf.py
  fail_on_warning: false

python:
  install:
    - requirements: docs/requirements.txt